### ISSUE TITLE
Plax Responsive-ness

### ISSUE THREAD

**Issue by jaredrethman** [cameronmcefee/plax#39]
Hi Cameron,

Firstly, what a champion plugin, possibly one of my favorite jQuery plugins. I am currently building my portfolio, implementing your plugin. And everything is going great.

This isn't as much of an issue as it is rather a request on some advise. 

I'm trying to make the site responsive using css mediaqueries, but struggled to get the layers to update on resize() - I managed to get it to work when refreshed on an already resized window. But wanted to get it to work dynamically/instantly while resizing... anyway long story short...

I managed to achieve this by passing a function to on resize event - like so...

function disablePlax(){
    $.plax.disable({ "clearLayers": true })
    $('img.js-plaxify[style]').css('top', '');
    $('img.js-plaxify[style]').css('left', '');
    $('div.js-plaxify[style]').css('top', '');
    $('div.js-plaxify[style]').css('left', '');
}

and then start it up again, by calling the same function(s) called in document ready, like this:

function enablePlax(){
   var layers = $('.js-plaxify')
          $.each(layers, function(index, layer){
            $(layer).plaxify({
              xRange: $(layer).data('xrange') || 0,
              yRange: $(layer).data('yrange') || 0,
              invert: $(layer).data('invert') || false
            })
          })

```
    $.plax.enable();
```

}

I am a complete noob to jQuery, and am not sure if this is the best way to handle this sort of thing, but wanted to know if there was a better way of doing this. Or is it a case of "Don't fix if its not broken"?

Thanks again for Plax

**Comment by xaolas** [comment]
Its work on resize:
```javascript
    $('.forest__man, .forest__lens').plaxify();
    $.plax.enable();

    $(window).resize(function() {
        $('.forest__man, .forest__lens').removeAttr('style');
    });
```
