### ISSUE TITLE
Plain JS version?

### ISSUE THREAD

**Issue by bronzehedwick** [cameronmcefee/plax#64]
Any chance supporting a vanilla JavaScript version is on the roadmap?

**Comment by cameronmcefee** [comment]
Hi @bronzehedwick,

Plax is a backburner project for me at this point, so I don't currently have any such plans. I haven't touched Plax in a few years so it's entirely likely someone's written a better, vanilla js parallax plugin since then.

**Comment by bronzehedwick** [comment]
Gotcha, thanks!
