### ISSUE TITLE
Doesn't work with newest jQuery version

### ISSUE THREAD

**Issue by energyuser** [cameronmcefee/plax#66]
I've asked the same question on jQuery's repo:
https://github.com/jquery/jquery/issues/2460

**Comment by cameronmcefee** [comment]
Hi @energyuser,

Plax has been on the backburner for the last few years, so I won't likely be able to make updates any time soon. If you'd like to submit a pull request fixing the issue, I'm happy to review it.

**Comment by energyuser** [comment]
Sorry, I'm not that good in javascript. I hoped that you could update it but oh well...

**Comment by cameronmcefee** [comment]
Sorry, I can't be of more help at the moment :(. To be honest, Plax is pretty old. I'm willing to be there are better plugins out there. http://markdalgleish.com/projects/stellar.js/ Looks interesting.

**Comment by dmethvin** [comment]
It's possible this can be fixed by changing `plaxActivityTarget = $(window)` to `plaxActivityTarget = $(document.body)` but I'm not familiar enough with the code to test that hypothesis. 

Is this code still being used at GitHub? If so we'd want to be sure we didn't break it with a jQuery update. :smiling_imp:

**Comment by cameronmcefee** [comment]
Ha, looks as though it is. Guess I should prioritize this after all. Thanks @dmethvin I'll have a look at your suggestion.

**Comment by energyuser** [comment]
Thanks guys! I hope you come up with something and yes: https://github.com/404

**Comment by cameronmcefee** [comment]
@energyuser for your info, I may not be able to get to this for a few days (things are pretty busy on my end). If you're in a time crunch, I'd suggest looking at alternative plugins or trying to fix it yourself based on @dmethvin's suggestion.

**Comment by energyuser** [comment]
Yes, that worked as I commented above, perhaps you can change that in the code of the official plugin?

**Comment by cameronmcefee** [comment]
Should be fixed as of https://github.com/cameronmcefee/plax/commit/624c5ef8320293bc59582a3faf997d4fdc44cb75
