### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by WGRAY01** [cameronmcefee/plax#69]
First let me preface that I am VERY much a newbie here and to java script as well.
Although I love the script and its functionality. It doesn't seem to be responsive. If you size the window down narrower than the all of the elements they are off canvas.

So far the only way I can get it to somewhat work is by doing a reload.
`  window.addEventListener('resize', function () { 
    "use strict";
    window.location.reload(); 
	});`

This is a very archaic way of doing so.
Are there any other ways of accomplishing the re-positioning of the elements based on the window size?

**Comment by cameronmcefee** [comment]
Hi @WGRAY01,

You're probably right that there are better ways (something using css transforms comes to mind). As mentioned in the [README](https://github.com/cameronmcefee/plax/blob/master/readme.md), this hasn't been under active development for a few years, so it has very much fallen behind. If you're looking for a responsive option, you're better off looking at alternative libraries.
