### ISSUE TITLE
Can I use enable multi activityTarget?

### ISSUE THREAD

**Issue by sweettimes** [cameronmcefee/plax#70]
I have two block using plaxify, but I just use only one activity target..
How i can use multi activityTarget?

**Comment by cameronmcefee** [comment]
Hi @sweettimes,

Plax wasn't desiged to support multiple activity targets. I've seen people hack a solution together by including the file twice, but there are plenty of reasons why that's a bad idea. Plax hasn't been actively maintained for years, so you're probably better off finding a more current library that can do what you need it to do.
